### ISSUE TITLE
Add Nuget tool window icon

### ISSUE THREAD

**Issue by GauthierPLM** [jonathanlermitage/intellij-extra-toolwindow-colorful-icons-pub#1]
Currently, the Nuget icon is the default one provided by JetBrains.
A colorful one would be nice and make the icon easier to find.

**Comment by jonathanlermitage** [comment]
Sure, I can add it. Can you please provide a screenshot, just to be sure we're discussing the same icon? thanks.

**Comment by jonathanlermitage** [comment]
For the light theme, do you prefer 

the logo with the official color:
![image](https://github.com/user-attachments/assets/93b4ca75-c0a4-4cf8-9928-f2510e752691)

or the icon picked from IntelliJ's assets, which uses a different color (found here: https://intellij-icons.jetbrains.design/#NetIcons76-NuGet(Gray)):
![image](https://github.com/user-attachments/assets/08b107d4-feaf-46bd-8b66-d4cafd38e009)

**Comment by GauthierPLM** [comment]
I think the IntelliJ' asset looks better and is more in-line with the other colors used.

**Comment by jonathanlermitage** [comment]
Hi @GauthierPLM  
I just packaged a preliminary version with the NuGet tool window icon: [Extra ToolWindow Colorful Icons-2024.2.1.zip](https://github.com/user-attachments/files/16393630/Extra.ToolWindow.Colorful.Icons-2024.2.1.zip). Can you please tell me if this is OK for you?
To install this package, go to File > Settings > Plugins > the wheel icon > Install plugin from disk.  
Thanks!

**Comment by GauthierPLM** [comment]
Hi @jonathanlermitage,
It works well, thank you!
