### ISSUE TITLE
Add "running" indicators

### ISSUE THREAD

**Issue by daltojam** [jonathanlermitage/intellij-extra-toolwindow-colorful-icons-pub#2]
The default icons for CMake, Messages, Run, Debug, etc have a green dot in the corner to show when they are running. It would be nice to have this added to the icons in this plugin.

**Comment by jonathanlermitage** [comment]
Hi, I tried to build a project, and I can see the green dot over the build icon, like the red dot over the Problems icon if there are problems.  
These dots are added by the IDE.  
![image](https://github.com/user-attachments/assets/b93d7bf3-c8c9-49f5-9711-14a0aeb5dbf6)


Can you please share a screenshot? Just to be sure. I'm probably missing something ^^.

**Comment by daltojam** [comment]
Ah interesting. I didn't see it under over the "Messages" icon when I was running my build and assumed. Thanks for getting back to me so fast.
