### ISSUE TITLE
[Icon request] Tests tool window (Rider)

### ISSUE THREAD

**Issue by MrJul** [jonathanlermitage/intellij-extra-toolwindow-colorful-icons-pub#4]
First of all, thank you for bringing a bit of color in my day-to-day coding :)

It would be nice if the icon from the Tests tool window in Rider could get some color.
Icon:
![image](https://github.com/user-attachments/assets/0e864ace-a700-407a-832d-5784ecc8013b)

**Comment by MrJul** [comment]
Thank you for the quick reply!
That red-green icon looks very good to me, I don't think it needs further changes :) (And I say that despite being colorblind.)

**Comment by jonathanlermitage** [comment]
Thx! This will be part of the next plugin release, expected for next week.
