### ISSUE TITLE
Add new icons

### ISSUE THREAD

**Issue by ZHOUXING1997** [jonathanlermitage/intellij-extra-toolwindow-colorful-icons-pub#6]
vcs history icon, icon name is 'Show history'

![image](https://github.com/user-attachments/assets/8c22c17c-9a24-4794-bf10-6392e5751d1c)

**Comment by jonathanlermitage** [comment]
Implemented. This will be part of the 2025.1.1 release, which is expected for January.

A preview:
![image](https://github.com/user-attachments/assets/f48c3d57-36e2-44c8-bb4e-348580fa3f42)
